deploymentName: configserver-deployment
serviceName: configserver-deployment
appLabel: configserver
appName: configserver

replicaCount: 1

image:
  repository: satish2121/configserver
  tag: banking

containerPort: 8071

service:
  type: ClusterIP
  port: 8071
  targetPort: 8071

appname_enabled: true
profile_enabled: false
config_enabled: false
eureka_enabled: false
authserver_enabled: false
otel_enabled: true
kafka_enabled: false

