spring:
  application:
    name: "gatewayserver"
  config:
    import: "configserver:http://localhost:8071/"
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

info:
  app:
    name: "gatewayserver"
    description: "Banking application Gateway Server"
    version: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

logging:
  level:
    com:
      satish:
        gatewayserver: DEBUG
