deploymentName: cards-deployment
serviceName: cards-deployment
appLabel: cards
appName: cards

replicaCount: 1

image:
  repository: satish2121/cards
  tag: banking

containerPort: 9000

service:
  type: ClusterIP
  port: 9000
  targetPort: 9000

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
authserver_enabled: false
otel_enabled: true
kafka_enabled: false

