deploymentName: accounts-deployment
serviceName: accounts-deployment
appLabel: accounts
appName: accounts

replicaCount: 1

image:
  repository: satish2121/accounts
  tag: banking

containerPort: 8080

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
authserver_enabled: false
otel_enabled: true
kafka_enabled: true

