server:
  port: 8080
spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:postgresql://localhost:5435/accounts
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  profiles:
    active: "prod"
  config:
    import: "configserver:http://localhost:8071/"