server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/accounts
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  profiles:
    active: "prod"

build:
  version: "3.0"
accounts:
  message: "Welcome to Banking accounts application"
  contactDetails:
    name: "Satish Subudhi"
    email: "satishsubudhi522@gmail.com"
  callSupport:
    - (+91)7873482121
    - (+91)7008378517