server:
  port: 8080
  shutdown: graceful
spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:postgresql://localhost:5435/accounts
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  #profiles:
  #  active: "qa"
  config:
    import: "configserver:http://configserver:8071/"
  rabbitmq:
    host: "localhost"
    port: "5672"
    password: "guest"
    username: "guest"
  lifecycle:
    timeout-per-shutdown-phase: 30s

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "accounts"
    description: "Banking application"
    version: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  #Enable shutdown related properties in actuator
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

#Shutdown related api to enable
endpoints:
  shutdown:
    enabled: true

logging:
  level:
    com:
      satish:
        accounts: DEBUG