deploymentName: eurekaserver-deployment
serviceName: eurekaserver-deployment
appLabel: eurekaserver
appName: eurekaserver

replicaCount: 1

image:
  repository: satish2121/discoveryserver
  tag: banking

containerPort: 8070

service:
  type: ClusterIP
  port: 8070
  targetPort: 8070

appname_enabled: true
profile_enabled: false
config_enabled: true
eureka_enabled: false
authserver_enabled: false
otel_enabled: true
kafka_enabled: false

