services:
  network-deploy-service:
    networks:
      - satish
  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
#    environment:
#      JAVA_TOOL_OPTIONS: "-javaagent:/app/libs/opentelemetry-javaagent-2.10.0.jar -Dotel.exporter.otlp.endpoint=http://tempo:4318"
#      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318
#      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
#      OTEL_LOGS_EXPORTER: none
#      OTEL_METRICS_EXPORTER: none

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-accounts:5432/accounts"
      SPRING_RABBITMQ_HOST: "rabbitmq"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discoveryserver:8070/eureka/"

  microservice-eureka-config:
    extends:
      service: microservice-configserver-config
    depends_on:
      discoveryserver:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryserver:8070/eureka/


