apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver
  labels:
    app: gatewayserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayserver
  template:
    metadata:
      labels:
        app: gatewayserver
    spec:
      containers:
      - name: gatewayserver
        image: satish2121/gatewayserver:banking
        ports:
        - containerPort: 8072
        volumeMounts:
        - name: banking-configmap
          mountPath: /config
        env:
          - name: SPRING_APPLICATION_NAME
            valueFrom:
              configMapKeyRef:
                name: banking-configmap
                key: GATEWAY_APPLICATION_NAME
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef:
                name: banking-configmap
                key: SPRING_CONFIG_IMPORT
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: banking-configmap
                key: SPRING_PROFILES_ACTIVE
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef:
                name: banking-configmap
                key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
            valueFrom:
              configMapKeyRef:
                name: banking-configmap
                key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
      volumes:
      - name: banking-configmap
        configMap:
          name: banking-configmap                

---
apiVersion: v1
kind: Service
metadata:
  name: gatewayserver
spec: 
  selector:
    app: gatewayserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8072
      targetPort: 8072
      
