deploymentName: notification-deployment
serviceName: notification-deployment
appLabel: notification
appName: notification

replicaCount: 1

image:
  repository: satish2121/notification
  tag: banking

containerPort: 9010

service:
  type: ClusterIP
  port: 9010
  targetPort: 9010

appname_enabled: true
profile_enabled: false
config_enabled: false
eureka_enabled: false
authserver_enabled: false
otel_enabled: false
kafka_enabled: true

