deploymentName: loans-deployment
serviceName: loans-deployment
appLabel: loans
appName: loans

replicaCount: 1

image:
  repository: satish2121/loans
  tag: banking

containerPort: 8090

service:
  type: ClusterIP
  port: 8090
  targetPort: 8090

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
authserver_enabled: false
otel_enabled: true
kafka_enabled: false

