services:
  network-deploy-service:
    networks:
      - satish
  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
  microservice-configserver-config:
    extends: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-accounts:5432/accounts"
      SPRING_RABBITMQ_HOST: "rabbitmq"


